LOD/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('data_display/', include('data_display.urls')),
	path('account/', include('account.urls')),
]

account/urls.py
from . import views
from django.conf.urls import url
 
app_name = 'account'

urlpatterns = [
    url(r'^signup/',views.signup_view,name='signup'),
    url(r'^login/',views.login_view,name='login'),
	url(r'^logout/',views.logout_view,name='logout'),
	url(r'',views.index,name='index'),
	
]

data_display/urls.py
from django.urls import path
from . import views

app_name = 'data_display'
urlpatterns = [
    path('', views.index, name='index'),
	path('changed', views.changed,name='changed'),
	path('search', views.search,name='search'),
	path('infoDisplay/<type>/<id>', views.infoDisplay,name='infoDisplay'),
    path('<type>/<amount>/<offset>', views.index, name='index'),

]

data_display/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class changes(models.Model):

    class Meta:
        verbose_name_plural = "changes"
		
    id= models.IntegerField(primary_key=True)
    targetUri = models.URLField(max_length=300)
    attributeName = models.CharField(max_length=200)
    oldValue = models.CharField(max_length=200)
    newValue = models.CharField(max_length=200)
    dateCreated = models.DateTimeField(auto_now_add=True)
    dateModified = models.DateTimeField(auto_now=True)
    userId = models.IntegerField()
	
    def __str__(self):
        return 'object '  +str(self.id) + ' modified/created by:User ' + str(self.userId)

data_display/forms.py
from django import forms
from . import models

class changeForm(forms.ModelForm):
    
    class Meta:
        model = models.changes
        fields = ['newValue']

data_display/views.py
import json
import requests
import datetime as dt
import rdflib
from rdflib.graph import Graph
from SPARQLWrapper import SPARQLWrapper,JSON
from . import models
from django.shortcuts import render
from collections import defaultdict
from . import forms
from django.contrib.auth.decorators import login_required
from data_display.models import changes
from django.shortcuts import get_object_or_404
from django.contrib.auth.forms import AuthenticationForm



names = ['Questionnaire','Question','PaperSlip','Source','Multimedia','PaperSlip Record','Lemma','Person']

def index(request,type=None,amount=None,offset=None):
    url2 = "http://exploreat.adaptcentre.ie/"
    
    if request.method == 'POST':
	
        try:
            #left arrow navigation is triggered
            left = request.POST['left']
            type = request.POST['type']
            amount=request.POST['amount']
            amountN = int(amount)+int(left)
            if amount==10:
                newUrl = url2 + type

                context = getAllInfo(newUrl,10,1,type)
                return render(request, 'data_display/index.html',context)
            offset=request.POST['offset']
            offsetN = int(offset)+int(left)
            newUrl = url2 + type

            context = getAllInfo(newUrl,amountN,offsetN,type)
            return render(request, 'data_display/index.html',context)
        except:
            print("using right arrow")
        try:
            #right arrow navigation is triggered
            right = request.POST['right']
            type = request.POST['type']
            amount=request.POST['amount']
            amountN = int(amount)+int(right)
            offset=request.POST['offset']
            offsetN = int(offset)+int(right)
            newUrl = url2 + type
            
            context = getAllInfo(newUrl,amount,offsetN,type)
            
            return render(request, 'data_display/index.html',context)
        except:
            print("using left arrow")
			
		
        strUrl='http://exploreat.adaptcentre.ie/'
        strUrl+=str(request.POST.get('type'))
        strUrl+='/'+str(request.POST.get('id'))
        context = retData(strUrl)
        return render(request, 'data_display/dataDisplay.html',context)
    if type != None:
        newUrl = url2 + type
        context = getAllInfo(newUrl,amount,offset,type)
        context["displayCards"] = True;
        return render(request, 'data_display/index.html',context)
       
    if request.user.is_authenticated:
        username = request.user.username
        loggedIn = True
        context = {'username':username,'loggedIn':loggedIn}
    else:
        context = {'loggedIn':False}
        form = AuthenticationForm()
        context['form']=form
		
    return render(request, 'data_display/home.html',context)
	
def search(request):
    dataset="http://localhost:3030/dboe/query"
    subject = request.POST['type']
    predicate = request.POST['select2']
    object = request.POST['val']
    
    #the query will strip the questionnaire number and replace http://localhost/oldca/fragebogen/1 in the query
    sparql = SPARQLWrapper(dataset)
    sparql.setQuery("""
	
                    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
                    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
                    prefix oldcan: <https://explorations4u.acdh.oeaw.ac.at/ontology/oldcan#>
				
                    SELECT *
					from Named <http://exploreat.adaptcentre.ie/Questionnaire_graph>
                    WHERE {
					 Graph <http://exploreat.adaptcentre.ie/Questionnaire_graph>{
							?s rdf:type oldcan:""" + subject +""".
							?s """ + predicate +""" ?o .
							Filter regex(?o, \"""" + object +"""\" ,"i").
							
						}
					} 
					limit 10
                 """)
    sparql.setReturnFormat(JSON)
    results = sparql.query().convert()
    
    context = {}
    index =0;
    length = len(results['results']['bindings'])
    for i in range(0,length):
        context[i] = results['results']['bindings'][i]['s']['value'];
    
    context['range'] = range(0,length);
    return render(request, 'data_display/index.html',context)

def infoDisplay(request,type,id):
    defaultStrUrl='http://exploreat.adaptcentre.ie/'

    if request.method == 'POST':
        strUrl='http://exploreat.adaptcentre.ie/'+type+'/'+id
        strUrl+=str(request.POST.get('typeValue'))
        strUrl+='/'+str(request.POST.get('id'))
        
        context = retData(strUrl)
        return render(request, 'data_display/index.html',context)
    context = retData('http://exploreat.adaptcentre.ie/'+type+'/'+id)
    context['targetUri'] = 'http://exploreat.adaptcentre.ie/'+type+'/'+id
    return render(request, 'data_display/dataDisplay.html',context)

# function used to create single words instead of long urls	
def word(string,findCharacter,secondCharacter):
    if string.rfind(findCharacter) == -1:
        position = string.rfind(secondCharacter)
    else:
        position = string.rfind(findCharacter)
    position += 1
    if position == -1:
        return string
    return string[position:len(string)]
	
def findName(stringUrl):
    position = stringUrl.rfind('/')
    return stringUrl[position+1:len(stringUrl)]
	
# function gets all the data from a given url, will create a type,value and shortname key. all keys have values of lists which contain the info from the url
def retData(stringUrl):
    
    data={}
    response = requests.get(stringUrl)
    todos = json.loads(response.text)
    results = ""
    results = todos["results"]
    bindings = todos["results"]["bindings"]
   
    i=0
    type=[]
    value=[]
    shortname=[]
    for binding in bindings:
        
        type.append(binding['p']['type'])
        shortname.append(word(binding['p']['value'],'#','/'))
        value.append(binding['p']['value'])
		
        type.append(binding['o']['type'])
        value.append(binding['o']['value'])
        shortname.append(word(binding['o']['value'],'#','/'))
        
        if word(binding['p']['value'],'#','/') == 'label':
            data['name'] = binding['o']['value']

        data[i] = {
                'type':type,
			    'value':value,
			    'shortname':shortname
            }
        
        i+=1
        type=[]
        value=[]
        shortname=[]
	
    data['id'] = findName(stringUrl)
    data['range'] = range(0,len(data)-2)
    data['form'] = forms.changeForm()
    """
        example dictionary created by retData, each bit of info from the entity will have a sub dictionary telling the user of the type and value
        ,shortnames is there for display purposes. notice how in the sub-dictionary (0) that value[0] = 'http://www.w3.org/2000/01/rdf-schema#label' this is the prediacte
        with the object value = value[1], type[0] tell us that the predicate value is a uri and the corresponding object value is a literal
    {
        'name': 'Fragebogen 2: Die Osterwoche (1)', 
        0:  {
                'type': ['uri', 'literal'], 
                'value': ['http://www.w3.org/2000/01/rdf-schema#label', 'Fragebogen 2: Die Osterwoche (1)'], 
                'shortname': ['label', 'Fragebogen 2: Die Osterwoche (1)']
            }, 
        1:  {
                'type': ['uri', 'literal'], 
                'value': ['https://explorations4u.acdh.oeaw.ac.at/ontology/oldcan#note', 'bafb2'], 
                'shortname': ['note', 'bafb2']
            }, 
        2:  {
                'type': ['uri', 'uri'], 
                'value': ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'https://explorations4u.acdh.oeaw.ac.at/ontology/oldcan#Questionnaire'],
                'shortname': ['type', 'Questionnaire']
            }, 
        3:  {
                'type': ['uri', 'uri'],
                'value': ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'https://explorations4u.acdh.oeaw.ac.at/ontology/oldcan#SystematicQuestionnaire'],
                'shortname': ['type', 'SystematicQuestionnaire']
            }, 
        4:  {
                'type': ['uri', 'literal'], 
                'value': ['https://explorations4u.acdh.oeaw.ac.at/ontology/oldcan#title', 'Fragebogen 2: Die Osterwoche (1)'],
                'shortname': ['title', 'Fragebogen 2: Die Osterwoche (1)']
            }, 
        5:  {
                'type': ['uri', 'uri'], 
                'value': ['https://explorations4u.acdh.oeaw.ac.at/ontology/oldcan#hasAuthor', 'http://exploreat.adaptcentre.ie/Person/22192'], 
                'shortname': ['hasAuthor', '22192']
            }, 
        6:  {
                'type': ['uri', 'literal'], 
                'value': ['https://explorations4u.acdh.oeaw.ac.at/ontology/oldcan#publicationYear', '1920'], 
                'shortname': ['publicationYear', '1920']
            }, 
        'id': '2', 
        'range': range(0, 7), 
        'form': <changeForm bound=False, valid=Unknown, fields=(newValue)>
	}
		form in this case will have values from forms.py (just newValue)
        range(0,7) is because the entity contained 6 piece of information
    """
    return data
	
def getAllInfo(url,amount,offset,type):
    # getAllInfo is used to gather 10 subjects of an entity. ie, the first 10 questionnaires etc. 
    newUrl = url + '/' + str(amount) + '/' + str(offset)
    # newUrl could look like https//:explo...../Questionnaire/10/1
    data={} #empty dictionary to store teh subjects we recieve
    
    response = requests.get(newUrl)
    todos = json.loads(response.text)
    results = ""
    results = todos["results"]
    bindings = todos["results"]["bindings"]
    index = 0
    # the returned JSON actually contains repetitions of the same url, so we check for duplicates with checkDataContained(which takes in the current dictionary, and the value to test for)
    for binding in bindings:
        if checkDataContained(data,binding['s']['value']) != True:
            data[index] = binding['s']['value']
            index += 1
    data['range'] = range(0,index)

data_display/templates/data_display/base.html
{% load search_filter %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'css/DDStyle.css' %}" type="text/css">
		<link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">
	</head>
	<body>

		<div class="topnav" id="myTopnav">
			<a href="#home" class="active">
				<img src="{% static 'images/logo.png' %}" class="d-inline-block align-top" alt="">
			</a>
			{% if not loggedIn %}
				<form action="{% url 'account:login' %}" class="menuItem">
					{% csrf_token %}
					<button>Sign In<i style="margin:2px;" class="fa fa-sign-out"></i></button>
				</form>
			{% else %}
				<form action="{% url 'account:logout' %}" class="menuItem">
					{% csrf_token %}
					<button>logout<i style="margin:2px;" class="fa fa-sign-out"></i></button>
				</form>
				<form action="{% url 'account:signup' %}" class="menuItem">
					{% csrf_token %}
					<button id="name" disabled>{{username}}</button>
				</form>
			{% endif %}


			<form method="post" action="{% url 'data_display:search' %}" class="form-inline menuItem" >
				{% csrf_token %}
				<select name="type" id="select1" class="formInputs">
					<option value="Questionnaire">Questionnaire</option>
					<option value="Question">Question</option>
					<option value="Source">Source</option>
					<option value="Multimedia">Multimedia</option>
					<option value="PaperSlip">PaperSlip</option>
					<option value="PaperSlipRecord">PaperSlipRecord</option>
					<option value="Lemma">Lemma</option>
					<option value="Person">Person</option>
				</select>
				<select name="select2" id="select2" class="formInputs">
					<option value="rdfs:label">Label</option>
					<option value="oldcan:note">Note</option>
					<option value="rdf:type">Type</option>
					<option value="oldcan:title">Title</option>
					<option value="oldcan:hasAuthor">Has Author</option>
					<option value="oldcan:publicationYear">Publication Year</option>
					<option value="oldcan:hasMultimedia">Has Multimedia</option>
				</select>
				<input type="text" class="formInputs" name="val" id="textInput" placeholder="Enter Value" aria-label="Search" style="color:white;">
				<button type="submit" class="formInputs" id="formButton"><i class="fa fa-search"></i></button>
			</form>
			<a style="font-size:15px;" class="icon"><i class="fa fa-bars"></i></a>
		</div>
		
		<div class="container-fluid" >
			<div class="row">
				<div class="col-2" id="sideM">
					<ul id="sideMenu" >
						<li>
							<a href="{% url 'data_display:index' type='Questionnaire' amount=10 offset=1 %}" >Questionnaires</a>
						</li>
						<li>
							<a href="{% url 'data_display:index' type='Question' amount=10 offset=1 %}" >Questions</a>
						</li>
						<li>
							<a href="{% url 'data_display:index' type='Source' amount=10 offset=1 %}" >Sources</a>
						</li>
						<li>
							<a href="{% url 'data_display:index' type='Multimedia' amount=10 offset=1 %}" >Multimedias</a>
						</li>
						<li>
							<a href="{% url 'data_display:index' type='PaperSlip' amount=10 offset=1 %}" >PaperSlips</a>
						</li>
						<li>
							<a href="{% url 'data_display:index' type='PaperSlipRecord' amount=10 offset=1 %}" >PaperSlip Records</a>
						</li>
						<li>
							<a href="{% url 'data_display:index' type='Lemma' amount=10 offset=1 %}" >Lemmas</a>
						</li>
						<li>
							<a href="{% url 'data_display:index' type='Person' amount=10 offset=1 %}" >Persons</a>
						</li>
					</ul>
				</div>
				<div class="row mobileVersion" >
					<div class="navigate">
						<button class="dropBtn">Questionnaire<i class="fa fa-caret-down"></i></button>
						<div class="dropdown-content">
							<a class="dropdown-item" href="{% url 'data_display:index' type='Questionnaire' amount=10 offset=1 %}">Questionnaires</a>
								<a href="{% url 'data_display:index' type='Question' amount=10 offset=1 %}">Questions</a>
								<a href="{% url 'data_display:index' type='Source' amount=10 offset=1 %}">Sources</a>
								<a href="{% url 'data_display:index' type='Multimedia' amount=10 offset=1 %}">Multimedias</a>
								<a href="{% url 'data_display:index' type='PaperSlip' amount=10 offset=1 %}">PaperSlips</a>
								<a href="{% url 'data_display:index' type='PaperSlipRecord' amount=10 offset=1 %}">PaperSlip Records</a>
								<a href="{% url 'data_display:index' type='Lemma' amount=10 offset=1 %}">Lemmas</a>
								<a href="{% url 'data_display:index' type='Person' amount=10 offset=1 %}">Persons</a>
						</div>
					</div>
				</div>
				{% block content %}
				{% endblock %}
			</div>
			<hr>
			{% if displayCards %}
				<div class="row">
					<div class="btn-container">
						<div class="navigation" >
							<a href="{% backTen amount offset type%}" class="btn"><i class="fa fa-arrow-left" style="color:white;"></i></a>
							<a href="{% forwardTen amount offset type%}" class="btn" ><i class="fa fa-arrow-right" style="color:white;"></i></a>
						</div>
					</div>
				</div>
			{% endif %}
			<div class="row">
				<footer>
					<ul>
						<li id="copyRights"><h4>Copy Right &copy 2018 ExploreAt Centre</h4></li>
						<li class="crImages"><img src="{% static 'images/dcu.png' %}" width="60px;" height="60px" /></li>
						<li class="crImages"><img src="{% static 'images/ucd.jpg' %}" width="60px;" height="60px" /></li>
						<li class="crImages"><img src="{% static 'images/dit.jpg' %}" width="60px;" height="60px" /></li>
						<li class="crImages"><img src="{% static 'images/trinity.jpg' %}" width="60px;" height="60px" /></li>
					</ul>
				</footer>
			</div>
		</div>

		
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
		<script src="{% static 'script/DDJQuery.js' %}" ></script>
	</body>
</html>

data_display/templates/data_display/dataDisplay.html
{% extends 'data_display/base.html' %}
{% load search_filter %}
{% load staticfiles %}
{% block content %}
		<!-- a dictionary will be parsed into here containing all information about a subject(subject could be Questionnaire/1) therefore all information about 
			Questionnaire/1 such as label, title, date etc is put into a dictionary and parsed into here
		-->
		<div class="col-10" >
			<div class="col-5 tableBox" >
				<h2>{{name}}</h2>

					{% for firstIndex in range %} <!-- range return a range data type from the dictionary ie, how many subjects were in the url -->
					
						{% getListLength as listRange %} <!-- template tag(getListLength) returns listRange as a range datatype of 0-2 -->
						<div class="infoBox"> <!-- each tr will contain to bit of info -->
							{% for secondIndex in listRange %} 
									<!-- this for loop reads the first value and determines if it is a 'uri' , if true then condition is true -->
									{% typeTest firstIndex secondIndex as condition%}
									{% if condition %}
										<!-- will create a link -->
										{% getData firstIndex 'value' secondIndex as urlData %}
										{% getData firstIndex 'shortname' secondIndex as wordData %}
										
										{% imageTest wordData as testIfImage %} <!-- test to see if the wordData contains a .png or .jpg -->
										{% moduloTest firstIndex as modTest %}
										{% if testIfImage %} <!-- if it did contain a .png or .jpg -->
											<!-- will create a piece of table data in a table row with a url link -->
												<p><a href="{% test urlData %}" data-toggle="tooltip" data-html="true" title="{% extraction urlData %}">{{wordData}}</a></p>
											<!-- test is a pattern matching regex to determine if the given url could be used to navigate to other piece of info related to
											the enitity. such as Questionnaire having an author 
											-->
											{% addImageSource wordData%} <!-- since wordData did contain a .jpg or .png the list data type(which is default 0) will increment to 
											indicate that there is an image to display 
											-->
										{% else %}
												<p><a href="{% test urlData %}" data-toggle="tooltip" data-html="true" title="{% extraction urlData %}">{{wordData}}</a></p>
										{% endif %}
									{% else %} 
										<!-- getting to this else means that the tested value was not a uri. therefor the p(tag) will be created 
										normally with no additional navigation links. however it must still be tested for a possible .png or .jpg-->
										{% getData firstIndex 'shortname' secondIndex as wordData %}
										{% imageTest wordData as testIfImage2 %}
										{% if testIfImage2 %} <!-- this if statement is needed to create the data-id which is used to display the images -->
												<p>{{wordData}}<i class="fa fa-image testClass" data-id="{% makeImageName %}" data-toggle="tooltip" title="Show Image" style="margin-left:3px;"></i></p>
											{% addImageSource wordData%}
										{% else %}
												<p>{{wordData}}</p>
										{% endif %}
									{% endif %}
							{% endfor %}
							<span><i class="fa fa-pencil saveIcons" data-id="{% makeName firstIndex %}" data-id="{% makeImageName %}" data-toggle="tooltip" title="Edit data" ></i></span>
							<span style="display:none;" id="{% makeName firstIndex %}">
								<form class="changeData" action="{% url 'data_display:changed' %}" method="post">
									{% csrf_token %}
									{% for field in form %} <!-- form in this case will have one value to display(newValue) -->
										<div class="form-group">
											<input type="text" class="form-data" name="{{field.html_name}}" placeholder="New Value" >
											<input type="hidden" class="form-data" name="id" value="{{id}}">
											<input type="hidden" class="form-data" name="targetUri" value="{% getData firstIndex 'value' 0 %}"> 
											<!-- getData is a template tag which will retrieve the information for the form -->
											<input type="hidden"  class="form-data" name="attributeName" value="{% getData firstIndex 'shortname' 0 %}">
											<input type="hidden"  class="form-data" name="oldValue" value="{% getData firstIndex 'shortname' 1 %}">
											<button type="submit" class="form-data"><i class="fa fa-save"></i></button>
											{{ field.errors}}
										</div>
									{% endfor %}
								</form>
							</span>
						</div>
					{% endfor %}
			</div>
			<div class="col-5 tableBox" >
			{% imagesRange as ranges %}
			{% for i in ranges %}
			    <img src="{% static 'images/person.jpg' %}" class="imageBox" id="{% makeNewImageName i %}" style="display:none;"/>
			{% endfor %}
			</div>
		</div>

{% endblock %}

data_display/templates/data_display/edit.html
{% extends 'data_display/base.html' %}
{% load search_filter %}
{% load staticfiles %}
        {% block content %}
		<div class="col-7 col-md-7">
			<div class="container mr-2">
				<table class="table table-bordered">
					<tbody>
					<thead class="thead-dark">
						<tr>
						  <th scope="col">{{name}} {{id}}</th>
						</tr>
					</thead>
					{% for firstIndex in range %} <!-- range return a range data type from the dictionary ie, how many subjects were in the url -->
					
						{% getListLength as listRange %} <!-- templatetag(getListLength) returns listRange as a range datatype of 0-2 -->
						<tr>
						{% for secondIndex in listRange %} 
								<!-- this for loop reads the first value and determines if it is a 'uri' , if true then condition is true -->
								{% typeTest firstIndex secondIndex as condition%}
								{% if condition %}
									{% getData firstIndex 'value' secondIndex as urlData %}
									{% getData firstIndex 'shortname' secondIndex as wordData %}
									<!-- will create a link -->
									<td><a href="{{ urlData }}" data-toggle="tooltip" data-html="true" title="{% extraction urlData %}">{{wordData}}</a></td>
								{% else %}
									{% getData firstIndex 'shortname' secondIndex as wordData %}
									<td>{{wordData}}</td>
								{% endif %}
						{% endfor %}
						</tr>
					{% endfor %}
					</tbody>
				</table>
				
				<form action="{% url 'data_display:changed' %}" method="post">
					{% csrf_token %}
					{{form}}
				    <input type="submit" name="submit">
					<input type="hidden" name="contextValues" value="{{ context }}">
				    <button class="btn btn-primary" type="button">Make Edit</button>
				</form>
			</div>
		</div>
	{% endblock %}

data_display/templates/data_display/home.html
{% extends 'data_display/base.html' %}
{% load search_filter %}
{% load staticfiles %}
{% block content %}
<div class="col-10">
	<div class="cent">
		<div class="sign" id="login">
			<form action="{% url 'account:login' %}" method="post">
				{% csrf_token %}
				<h4>Login</h4>
				{% for field in form %}
					<label>{{ field.html_name }}</label>
					{{ field }}
					<br>
				{% endfor %}
				<button type="submit">Login</button>
			</form>
		</div>
	</div>
</div>


{% endblock %}

data_display/templates/data_display/index.html
{% extends 'data_display/base.html' %}
{% load search_filter %}
{% load staticfiles %}
{% block content %}
		<!-- a dictionary will be parsed into this section containing 10 subjects --> 
		<div class="col-10 " id="content">
			<div class="container-fluid">
				{% for i in range %} <!-- range returns a range data type from the dictionary ie, how many subjects were in the url -->
					<div class="card">
						<div class="card-header">{% getTitle type i%}</div> <!-- get the title of the subject -->
						<ul class="list-group list-group-flush">
							{% rangeForIndex as rangeTwo%} <!-- will return a range (0,3) this is to display 3 pieces of info per car -->
							{% for j in rangeTwo %}
								<li class="list-group-item " >{% getInfoForIndex i j%}</li>	
							{% endfor %}
						</ul>
						{% getTypeForIndex i True as type %} 
						{% makeUrl type as url%} <!-- creates a url for naviagtion -->
						<a href="{{url}}" class="VMbutton">View more</a>
					</div>
				{% endfor %}
			</div>
		</div>
	
{% endblock %}